#!/bin/bash

set -e

pushd dutyfree/warehouse
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

  go mod download

  golangci-lint run
popd
