#!/bin/bash

set -e

pushd resource-types-website
  git config --global user.email "concourseteam+concourse-github-bot@gmail.com"
  git config --global user.name "Concourse Bot"
  make update-resources
popd
